export {
    CircleSlash2Icon as CancelledIcon,
    CircleCheckBigIcon as CompletedIcon,
    CirclePlusIcon as CreatedIcon,
    NetworkIcon as DependsOnIcon,
    GoalIcon as DueIcon,
    FileTextIcon as FileIcon,
    SignatureIcon as IdIcon,
    CircleAlertIcon as OverdueIcon,
    CircleAlertIcon as PriorityIcon,
    RepeatIcon,
    HourglassIcon as ScheduledIcon,
    PlaneTakeoffIcon as StartedIcon,
    TagsIcon,
    CircleIcon as TaskIcon,
} from "lucide-preact";
